{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2008-5984"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "dia",
            "product": {
              "product_data": [
                {
                  "product_name": "dia",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "0.96.1"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "NVD-CWE-Other"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=504251"
        },
        {
          "url": "http://secunia.com/advisories/33672"
        },
        {
          "url": "http://secunia.com/advisories/33703"
        },
        {
          "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2009:040"
        },
        {
          "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2009:046"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2009/01/26/2"
        },
        {
          "url": "http://www.securityfocus.com/bid/33448"
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=481551"
        },
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/48262"
        },
        {
          "url": "https://www.redhat.com/archives/fedora-package-announce/2009-January/msg01065.html"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Untrusted search path vulnerability in the Python plugin in Dia 0.96.1, and possibly other versions, allows local users to execute arbitrary code via a Trojan horse Python file in the current working directory, related to a vulnerability in the PySys_SetArgv function (CVE-2008-5983)."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpeMatchString": "cpe:/a:dia:dia:0.96.1",
            "cpe23Uri": "cpe:2.3:a:dia:dia:0.96.1:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "vectorString": "(AV:L/AC:M/Au:N/C:C/I:C/A:C)",
        "accessVector": "LOCAL",
        "accessComplexity": "MEDIUM",
        "authentication": "NONE",
        "confidentialityImpact": "COMPLETE",
        "integrityImpact": "COMPLETE",
        "availabilityImpact": "COMPLETE",
        "baseScore": 6.9
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 3.4,
      "impactScore": 10.0,
      "obtainAllPrivilege": true,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2009-01-28T11:30Z",
  "lastModifiedDate": "2017-08-08T01:33Z"
}