{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2010-0628",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "mit",
            "product": {
              "product_data": [
                {
                  "product_name": "kerberos",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "5-1.7"
                      },
                      {
                        "version_value": "5-1.7.1"
                      },
                      {
                        "version_value": "5-1.8"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "NVD-CWE-Other"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://secunia.com/advisories/39023"
        },
        {
          "url": "http://web.mit.edu/kerberos/advisories/MITKRB5-SA-2010-002.txt"
        },
        {
          "url": "http://www.kb.cert.org/vuls/id/839413"
        },
        {
          "url": "http://www.securityfocus.com/archive/1/archive/1/510281/100/0/threaded"
        },
        {
          "url": "http://www.securityfocus.com/bid/38904"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-916-1"
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=566258"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The spnego_gss_accept_sec_context function in lib/gssapi/spnego/spnego_mech.c in the SPNEGO GSS-API functionality in MIT Kerberos 5 (aka krb5) 1.7 before 1.7.2 and 1.8 before 1.8.1 allows remote attackers to cause a denial of service (assertion failure and daemon crash) via an invalid packet that triggers incorrect preparation of an error token."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:mit:kerberos:5-1.7",
            "cpe23Uri": "cpe:2.3:a:mit:kerberos:5-1.7:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:mit:kerberos:5-1.7.1",
            "cpe23Uri": "cpe:2.3:a:mit:kerberos:5-1.7.1:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:mit:kerberos:5-1.8",
            "cpe23Uri": "cpe:2.3:a:mit:kerberos:5-1.8:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:L/Au:N/C:N/I:N/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 5.0
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 10.0,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2010-03-25T22:30Z",
  "lastModifiedDate": "2010-03-31T05:41Z"
}