{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2013-4111",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "openstack",
            "product": {
              "product_data": [
                {
                  "product_name": "python_glanceclient",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "0.9.0"
                      }
                    ]
                  }
                }
              ]
            }
          },
          {
            "vendor_name": "novell",
            "product": {
              "product_data": [
                {
                  "product_name": "opensuse",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "12.3"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-20"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://lists.opensuse.org/opensuse-updates/2013-08/msg00019.html"
        },
        {
          "url": "http://rhn.redhat.com/errata/RHSA-2013-1200.html"
        },
        {
          "url": "http://secunia.com/advisories/54313"
        },
        {
          "url": "http://secunia.com/advisories/54525"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-2004-1"
        },
        {
          "url": "https://bugs.launchpad.net/ossa/+bug/1192229"
        },
        {
          "url": "https://github.com/openstack/python-glanceclient/blob/master/doc/source/index.rst"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The Python client library for Glance (python-glanceclient) before 0.10.0 does not properly check the preverify_ok value, which prevents the server hostname from being verified with a domain name in the subject's Common Name (CN) or subjectAltName field of the X.509 certificate and allows man-in-the-middle attackers to spoof SSL servers via an arbitrary valid certificate."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": false,
            "cpe22Uri": "cpe:/a:openstack:python_glanceclient:0.4.0",
            "cpe23Uri": "cpe:2.3:a:openstack:python_glanceclient:0.4.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": false,
            "cpe22Uri": "cpe:/a:openstack:python_glanceclient:0.4.1",
            "cpe23Uri": "cpe:2.3:a:openstack:python_glanceclient:0.4.1:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": false,
            "cpe22Uri": "cpe:/a:openstack:python_glanceclient:0.4.2",
            "cpe23Uri": "cpe:2.3:a:openstack:python_glanceclient:0.4.2:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": false,
            "cpe22Uri": "cpe:/a:openstack:python_glanceclient:0.5.0",
            "cpe23Uri": "cpe:2.3:a:openstack:python_glanceclient:0.5.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": false,
            "cpe22Uri": "cpe:/a:openstack:python_glanceclient:0.5.1",
            "cpe23Uri": "cpe:2.3:a:openstack:python_glanceclient:0.5.1:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": false,
            "cpe22Uri": "cpe:/a:openstack:python_glanceclient:0.6.0",
            "cpe23Uri": "cpe:2.3:a:openstack:python_glanceclient:0.6.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": false,
            "cpe22Uri": "cpe:/a:openstack:python_glanceclient:0.7.0",
            "cpe23Uri": "cpe:2.3:a:openstack:python_glanceclient:0.7.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": false,
            "cpe22Uri": "cpe:/a:openstack:python_glanceclient:0.8.0",
            "cpe23Uri": "cpe:2.3:a:openstack:python_glanceclient:0.8.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:openstack:python_glanceclient:0.9.0",
            "cpe23Uri": "cpe:2.3:a:openstack:python_glanceclient:0.9.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/o:novell:opensuse:12.3",
            "cpe23Uri": "cpe:2.3:o:novell:opensuse:12.3:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:M/Au:N/C:P/I:P/A:N)",
        "accessVector": "NETWORK",
        "accessComplexity": "MEDIUM",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "NONE",
        "baseScore": 5.8
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 8.6,
      "impactScore": 4.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2013-08-28T21:55Z",
  "lastModifiedDate": "2013-10-31T03:34Z"
}