{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2009-2659",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "django_project",
            "product": {
              "product_data": [
                {
                  "product_name": "django",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "0.96"
                      },
                      {
                        "version_value": "1.0"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-22"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=539134"
        },
        {
          "url": "http://code.djangoproject.com/changeset/11353"
        },
        {
          "url": "http://secunia.com/advisories/36137"
        },
        {
          "url": "http://secunia.com/advisories/36153"
        },
        {
          "url": "http://www.djangoproject.com/weblog/2009/jul/28/security/"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2009/07/29/2"
        },
        {
          "url": "http://www.securityfocus.com/bid/35859"
        },
        {
          "url": "https://www.redhat.com/archives/fedora-package-announce/2009-August/msg00055.html"
        },
        {
          "url": "https://www.redhat.com/archives/fedora-package-announce/2009-August/msg00069.html"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The Admin media handler in core/servers/basehttp.py in Django 1.0 and 0.96 does not properly map URL requests to expected \"static media files,\" which allows remote attackers to conduct directory traversal attacks and read arbitrary files via a crafted URL."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:django_project:django:0.96",
            "cpe23Uri": "cpe:2.3:a:django_project:django:0.96:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:django_project:django:1.0",
            "cpe23Uri": "cpe:2.3:a:django_project:django:1.0:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:L/Au:N/C:P/I:N/A:N)",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "NONE",
        "availabilityImpact": "NONE",
        "baseScore": 5.0
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 10.0,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2009-08-04T16:30Z",
  "lastModifiedDate": "2009-08-12T05:30Z"
}