{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2008-1721"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "python_software_foundation",
            "product": {
              "product_data": [
                {
                  "product_name": "python",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "2.5.2"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-189"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://bugs.python.org/issue2586"
        },
        {
          "url": "http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html"
        },
        {
          "url": "http://secunia.com/advisories/29889"
        },
        {
          "url": "http://secunia.com/advisories/29955"
        },
        {
          "url": "http://secunia.com/advisories/30872"
        },
        {
          "url": "http://secunia.com/advisories/31255"
        },
        {
          "url": "http://secunia.com/advisories/31358"
        },
        {
          "url": "http://secunia.com/advisories/31365"
        },
        {
          "url": "http://secunia.com/advisories/33937"
        },
        {
          "url": "http://secunia.com/advisories/37471"
        },
        {
          "url": "http://secunia.com/advisories/38675"
        },
        {
          "url": "http://security.gentoo.org/glsa/glsa-200807-01.xml"
        },
        {
          "url": "http://securityreason.com/securityalert/3802"
        },
        {
          "url": "http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289"
        },
        {
          "url": "http://support.apple.com/kb/HT3438"
        },
        {
          "url": "http://support.avaya.com/css/P8/documents/100074697"
        },
        {
          "url": "http://wiki.rpath.com/wiki/Advisories:rPSA-2008-0149"
        },
        {
          "url": "http://www.debian.org/security/2008/dsa-1551"
        },
        {
          "url": "http://www.debian.org/security/2008/dsa-1620"
        },
        {
          "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2008:085"
        },
        {
          "url": "http://www.securityfocus.com/archive/1/archive/1/490690/100/0/threaded"
        },
        {
          "url": "http://www.securityfocus.com/archive/1/archive/1/507985/100/0/threaded"
        },
        {
          "url": "http://www.securityfocus.com/bid/28715"
        },
        {
          "url": "http://www.securitytracker.com/id?1019823"
        },
        {
          "url": "http://www.ubuntu.com/usn/usn-632-1"
        },
        {
          "url": "http://www.vmware.com/security/advisories/VMSA-2009-0016.html"
        },
        {
          "url": "http://www.vupen.com/english/advisories/2008/1229/references"
        },
        {
          "url": "http://www.vupen.com/english/advisories/2009/3316"
        },
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/41748"
        },
        {
          "url": "https://issues.rpath.com/browse/RPL-2444"
        },
        {
          "url": "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A8249"
        },
        {
          "url": "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A8494"
        },
        {
          "url": "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A9407"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Integer signedness error in the zlib extension module in Python 2.5.2 and earlier allows remote attackers to execute arbitrary code via a negative signed integer, which triggers insufficient memory allocation and a buffer overflow."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpeMatchString": "cpe:/a:python_software_foundation:python",
            "cpe23Uri": "cpe:2.3:a:python_software_foundation:python:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "2.5.2"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "vectorString": "(AV:N/AC:L/Au:N/C:P/I:P/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "baseScore": 7.5
      },
      "severity": "HIGH",
      "exploitabilityScore": 10.0,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2008-04-10T19:05Z",
  "lastModifiedDate": "2017-09-29T01:30Z"
}