{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2015-5652",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "python",
            "product": {
              "product_data": [
                {
                  "product_name": "python",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "3.5.0"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "NVD-CWE-Other"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://jvn.jp/en/jp/JVN49503705/995204/index.html"
        },
        {
          "url": "http://jvn.jp/en/jp/JVN49503705/index.html"
        },
        {
          "url": "http://jvndb.jvn.jp/jvndb/JVNDB-2015-000141"
        },
        {
          "url": "http://www.securityfocus.com/bid/76929"
        },
        {
          "url": "https://h20566.www2.hpe.com/portal/site/hpsc/public/kb/docDisplay?docId=emr_na-c05324755"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Untrusted search path vulnerability in python.exe in Python through 3.5.0 on Windows allows local users to gain privileges via a Trojan horse readline.pyd file in the current working directory.  NOTE: the vendor says \"It was determined that this is a longtime behavior of Python that cannot really be altered at this point.\""
        },
        {
          "lang": "en",
          "value": "<a href=\"https://cwe.mitre.org/data/definitions/426.html\">CWE-426: Untrusted Search Path</a>"
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "AND",
        "children": [
          {
            "operator": "OR",
            "cpe": [
              {
                "vulnerable": true,
                "cpe22Uri": "cpe:/a:python:python",
                "cpe23Uri": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "versionEndIncluding": "3.5.0"
              }
            ]
          },
          {
            "operator": "OR",
            "cpe": [
              {
                "vulnerable": false,
                "cpe22Uri": "cpe:/o:microsoft:windows",
                "cpe23Uri": "cpe:2.3:o:microsoft:windows:*:*:*:*:*:*:*:*"
              }
            ]
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:L/AC:L/Au:N/C:C/I:C/A:C)",
        "accessVector": "LOCAL",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "COMPLETE",
        "integrityImpact": "COMPLETE",
        "availabilityImpact": "COMPLETE",
        "baseScore": 7.2
      },
      "severity": "HIGH",
      "exploitabilityScore": 3.9,
      "impactScore": 10.0,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2015-10-06T01:59Z",
  "lastModifiedDate": "2016-11-28T19:35Z"
}