{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2012-2135",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "python",
            "product": {
              "product_data": [
                {
                  "product_name": "python",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "3.1"
                      },
                      {
                        "version_value": "3.1.1"
                      },
                      {
                        "version_value": "3.1.2"
                      },
                      {
                        "version_value": "3.1.5"
                      },
                      {
                        "version_value": "3.2"
                      },
                      {
                        "version_value": "3.2.3"
                      },
                      {
                        "version_value": "3.2.2150"
                      },
                      {
                        "version_value": "3.3"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "NVD-CWE-Other"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389"
        },
        {
          "url": "http://bugs.python.org/issue14579"
        },
        {
          "url": "http://secunia.com/advisories/51087"
        },
        {
          "url": "http://secunia.com/advisories/51089"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2012/04/25/2"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2012/04/25/4"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-1615-1"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-1616-1"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:3.1",
            "cpe23Uri": "cpe:2.3:a:python:python:3.1:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:3.1.1",
            "cpe23Uri": "cpe:2.3:a:python:python:3.1.1:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:3.1.2",
            "cpe23Uri": "cpe:2.3:a:python:python:3.1.2:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:3.1.5",
            "cpe23Uri": "cpe:2.3:a:python:python:3.1.5:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:3.2:alpha",
            "cpe23Uri": "cpe:2.3:a:python:python:3.2:alpha:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:3.2.3",
            "cpe23Uri": "cpe:2.3:a:python:python:3.2.3:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:3.2.2150",
            "cpe23Uri": "cpe:2.3:a:python:python:3.2.2150:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:3.3",
            "cpe23Uri": "cpe:2.3:a:python:python:3.3:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:3.3:beta2",
            "cpe23Uri": "cpe:2.3:a:python:python:3.3:beta2:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:L/Au:N/C:P/I:N/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 6.4
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 10.0,
      "impactScore": 4.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2012-08-14T22:55Z",
  "lastModifiedDate": "2013-05-15T03:25Z"
}