{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2014-9130",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "pyyaml",
            "product": {
              "product_data": [
                {
                  "product_name": "libyaml",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "0.1.5"
                      },
                      {
                        "version_value": "0.1.6"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-20"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://advisories.mageia.org/MGASA-2014-0508.html"
        },
        {
          "url": "http://linux.oracle.com/errata/ELSA-2015-0100.html"
        },
        {
          "url": "http://lists.opensuse.org/opensuse-updates/2015-02/msg00078.html"
        },
        {
          "url": "http://lists.opensuse.org/opensuse-updates/2016-04/msg00050.html"
        },
        {
          "url": "http://rhn.redhat.com/errata/RHSA-2015-0100.html"
        },
        {
          "url": "http://rhn.redhat.com/errata/RHSA-2015-0112.html"
        },
        {
          "url": "http://rhn.redhat.com/errata/RHSA-2015-0260.html"
        },
        {
          "url": "http://secunia.com/advisories/59947"
        },
        {
          "url": "http://secunia.com/advisories/60944"
        },
        {
          "url": "http://secunia.com/advisories/62164"
        },
        {
          "url": "http://secunia.com/advisories/62174"
        },
        {
          "url": "http://secunia.com/advisories/62176"
        },
        {
          "url": "http://secunia.com/advisories/62705"
        },
        {
          "url": "http://secunia.com/advisories/62723"
        },
        {
          "url": "http://secunia.com/advisories/62774"
        },
        {
          "url": "http://www.debian.org/security/2014/dsa-3102"
        },
        {
          "url": "http://www.debian.org/security/2014/dsa-3103"
        },
        {
          "url": "http://www.debian.org/security/2014/dsa-3115"
        },
        {
          "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2014:242"
        },
        {
          "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2015:060"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2014/11/28/1"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2014/11/28/8"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2014/11/29/3"
        },
        {
          "url": "http://www.securityfocus.com/bid/71349"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-2461-1"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-2461-2"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-2461-3"
        },
        {
          "url": "https://bitbucket.org/xi/libyaml/commits/2b9156756423e967cfd09a61d125d883fca6f4f2"
        },
        {
          "url": "https://bitbucket.org/xi/libyaml/issue/10/wrapped-strings-cause-assert-failure"
        },
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/99047"
        },
        {
          "url": "https://puppet.com/security/cve/cve-2014-9130"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "scanner.c in LibYAML 0.1.5 and 0.1.6, as used in the YAML-LibYAML (aka YAML-XS) module for Perl, allows context-dependent attackers to cause a denial of service (assertion failure and crash) via vectors involving line-wrapping."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:pyyaml:libyaml:0.1.5",
            "cpe23Uri": "cpe:2.3:a:pyyaml:libyaml:0.1.5:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:pyyaml:libyaml:0.1.6",
            "cpe23Uri": "cpe:2.3:a:pyyaml:libyaml:0.1.6:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:L/Au:N/C:N/I:N/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 5.0
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 10.0,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2014-12-08T16:59Z",
  "lastModifiedDate": "2017-12-09T02:29Z"
}