{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2009-3695",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "djangoproject",
            "product": {
              "product_data": [
                {
                  "product_name": "django",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "1.0"
                      },
                      {
                        "version_value": "1.1"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "NVD-CWE-Other"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=550457"
        },
        {
          "url": "http://groups.google.com/group/django-users/browse_thread/thread/15df9e45118dfc51/"
        },
        {
          "url": "http://secunia.com/advisories/36948"
        },
        {
          "url": "http://secunia.com/advisories/36968"
        },
        {
          "url": "http://www.debian.org/security/2009/dsa-1905"
        },
        {
          "url": "http://www.djangoproject.com/weblog/2009/oct/09/security/"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2009/10/13/6"
        },
        {
          "url": "http://www.securityfocus.com/bid/36655"
        },
        {
          "url": "http://www.vupen.com/english/advisories/2009/2871"
        },
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/53727"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Algorithmic complexity vulnerability in the forms library in Django 1.0 before 1.0.4 and 1.1 before 1.1.1 allows remote attackers to cause a denial of service (CPU consumption) via a crafted (1) EmailField (email address) or (2) URLField (URL) that triggers a large amount of backtracking in a regular expression."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:djangoproject:django:1.0",
            "cpe23Uri": "cpe:2.3:a:djangoproject:django:1.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:djangoproject:django:1.1",
            "cpe23Uri": "cpe:2.3:a:djangoproject:django:1.1:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:L/Au:N/C:N/I:N/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 5.0
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 10.0,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2009-10-13T10:30Z",
  "lastModifiedDate": "2017-08-17T01:31Z"
}